pipeline{
    agent any 
    stages{
        stage('checkout'){
            steps{
                git branch: 'DJango-application', url:'https://github.com/ManojKRISHNAPPA/reimagined-journey.git'
            }
        }

        stage('Docker image build'){
            steps{

                sh '''
                cd ecommerce
                docker build -t manojkrishnappa/djano-application:1 .
                '''
            }
        }
        stage('Containersation'){
            steps{
                sh '''
                    docker run -it -d -p 8000:8000 manojkrishnappa/djano-application:1
                '''
            }
        } 
        stage('Login to Docker Hub') {
                    steps {
                        script {
                            withCredentials([usernamePassword(credentialsId: 'docker-hub-credentials', usernameVariable: 'DOCKER_USERNAME', passwordVariable: 'DOCKER_PASSWORD')]) {
                                sh "echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin"
                            }
                        }
                    }
        } 
        stage('Pushing image to repository'){
            steps{
                sh 'docker push manojkrishnappa/djano-application:1'
            }
        }                     
    }
}